// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: claim.sql

package sql

import (
	"context"
)

const countClaimsByCoupon = `-- name: CountClaimsByCoupon :one
SELECT COUNT(*) FROM claims
WHERE coupon_name = $1
`

func (q *Queries) CountClaimsByCoupon(ctx context.Context, couponName string) (int64, error) {
	row := q.db.QueryRow(ctx, countClaimsByCoupon, couponName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClaim = `-- name: CreateClaim :one
INSERT INTO claims (user_id, coupon_name)
VALUES ($1, $2)
RETURNING id, user_id, coupon_name, claimed_at
`

type CreateClaimParams struct {
	UserID     string `json:"user_id"`
	CouponName string `json:"coupon_name"`
}

func (q *Queries) CreateClaim(ctx context.Context, arg CreateClaimParams) (Claim, error) {
	row := q.db.QueryRow(ctx, createClaim, arg.UserID, arg.CouponName)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CouponName,
		&i.ClaimedAt,
	)
	return i, err
}

const getClaimByUserAndCoupon = `-- name: GetClaimByUserAndCoupon :one
SELECT id, user_id, coupon_name, claimed_at FROM claims
WHERE user_id = $1 AND coupon_name = $2
LIMIT 1
`

type GetClaimByUserAndCouponParams struct {
	UserID     string `json:"user_id"`
	CouponName string `json:"coupon_name"`
}

func (q *Queries) GetClaimByUserAndCoupon(ctx context.Context, arg GetClaimByUserAndCouponParams) (Claim, error) {
	row := q.db.QueryRow(ctx, getClaimByUserAndCoupon, arg.UserID, arg.CouponName)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CouponName,
		&i.ClaimedAt,
	)
	return i, err
}

const listClaimedByCoupon = `-- name: ListClaimedByCoupon :many
SELECT user_id FROM claims
WHERE coupon_name = $1
ORDER BY claimed_at ASC
`

func (q *Queries) ListClaimedByCoupon(ctx context.Context, couponName string) ([]string, error) {
	rows, err := q.db.Query(ctx, listClaimedByCoupon, couponName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClaimsByCoupon = `-- name: ListClaimsByCoupon :many
SELECT id, user_id, coupon_name, claimed_at FROM claims
WHERE coupon_name = $1
ORDER BY claimed_at ASC
`

func (q *Queries) ListClaimsByCoupon(ctx context.Context, couponName string) ([]Claim, error) {
	rows, err := q.db.Query(ctx, listClaimsByCoupon, couponName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Claim
	for rows.Next() {
		var i Claim
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CouponName,
			&i.ClaimedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
