// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coupon.sql

package sql

import (
	"context"
)

const createCoupon = `-- name: CreateCoupon :one
INSERT INTO coupons (name, amount, remaining_amount)
VALUES ($1, $2, $2)
RETURNING id, name, amount, remaining_amount, created_at, updated_at
`

type CreateCouponParams struct {
	Name   string `json:"name"`
	Amount int32  `json:"amount"`
}

func (q *Queries) CreateCoupon(ctx context.Context, arg CreateCouponParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, createCoupon, arg.Name, arg.Amount)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.RemainingAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCoupon = `-- name: DeleteCoupon :exec
DELETE FROM coupons
WHERE name = $1
`

func (q *Queries) DeleteCoupon(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteCoupon, name)
	return err
}

const getCouponByName = `-- name: GetCouponByName :one
SELECT id, name, amount, remaining_amount, created_at, updated_at FROM coupons
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetCouponByName(ctx context.Context, name string) (Coupon, error) {
	row := q.db.QueryRow(ctx, getCouponByName, name)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.RemainingAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCouponForUpdate = `-- name: GetCouponForUpdate :one
SELECT id, name, amount, remaining_amount, created_at, updated_at FROM coupons
WHERE name = $1
FOR UPDATE
`

func (q *Queries) GetCouponForUpdate(ctx context.Context, name string) (Coupon, error) {
	row := q.db.QueryRow(ctx, getCouponForUpdate, name)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.RemainingAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllCoupons = `-- name: ListAllCoupons :many
SELECT id, name, amount, remaining_amount, created_at, updated_at FROM coupons
ORDER BY created_at DESC
`

func (q *Queries) ListAllCoupons(ctx context.Context) ([]Coupon, error) {
	rows, err := q.db.Query(ctx, listAllCoupons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Coupon
	for rows.Next() {
		var i Coupon
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.RemainingAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRemainingAmount = `-- name: UpdateRemainingAmount :one
UPDATE coupons
SET remaining_amount = $1
WHERE name = $2
RETURNING id, name, amount, remaining_amount, created_at, updated_at
`

type UpdateRemainingAmountParams struct {
	RemainingAmount int32  `json:"remaining_amount"`
	Name            string `json:"name"`
}

func (q *Queries) UpdateRemainingAmount(ctx context.Context, arg UpdateRemainingAmountParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, updateRemainingAmount, arg.RemainingAmount, arg.Name)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.RemainingAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
