// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Claim struct {
	ID         int32            `json:"id"`
	UserID     string           `json:"user_id"`
	CouponName string           `json:"coupon_name"`
	ClaimedAt  pgtype.Timestamp `json:"claimed_at"`
}

type Coupon struct {
	ID              int32            `json:"id"`
	Name            string           `json:"name"`
	Amount          int32            `json:"amount"`
	RemainingAmount int32            `json:"remaining_amount"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}
